### ISSUE TITLE
Missing Data?

### ISSUE THREAD

**Issue by matthewtownson** [jones139/covid-19#1]
Thanks for creating these and hosting them, they have been a great way to keep track of what's going on.

I have had a stab at running this so I can add my own areas of interest, but the code fails as it can't find some data on populations (populations.xlsx), is this something you generated at some point or can you point me to where to find it?

**Comment by jones139** [comment]
Hi Matthew,
My page links to the ONS populations data page here:  https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datasets/populationestimatesforukenglandandwalesscotlandandnorthernireland
The title of the file I have is for Mid 2018, using April 2019 local authority codes, but it looks like I must have re-named the ONS file to something simpler, sorry!

You are very welcome to modify it yourself, but if you want I can add an extra page of places you are interested in like my 'Family Interest' page.   I'm afraid the code is a bit hacky - should really have a configuration file to specify what to do, but it is all hard coded......

Cheers,
Graham.

**Comment by matthewtownson** [comment]
Thanks, I missed that it was on the website.

It's much easier to start with something than from scratch, so its a massive help.
